### ISSUE TITLE
目录修改建议

### ISSUE THREAD

**Issue by huajie1988** [0x2642/ourblog-new#4]
提议是否可建立一个公用文件夹作为对外入口，即将所有js，css,图片等资源统一放入其中作为静态文件夹，方便各处调用，另外最外层的views文件夹是否也可以如此操作，作为专用的404页面(可能需要试验)

**Comment by xykbear** [comment]
其实公用文件夹就是app那个，我把原来的名字改掉了，views内的文件生成后是能直接调用到的。
文件结构的话这样子如何：

> app
> │　index.html
> │
> ├─admin
> │　│　index.html
> │　│
> │　├─scripts
> │　│　　　app.js
> │　│
> │　└─styles
> │　　　　 main.css
> │
> ├─bower_components
> │
> ├─directive
> │
> ├─images
> │
> ├─scripts
> │　　　app.js
> │　　　controllers.js
> │　　　directive.js
> │　　　filter.js
> │　　　services.js
> │
> ├─styles
> │　　　main.css
> │　　　normalize.css
> │
> └─views

admin目录内的index.html引用库时：

``` HTML
  <!--引用公用库-->
  <script src="../bower_components/jquery/dist/jquery.min.js"></script>
  <!--引用私有库-->
  <script src="scripts/app.js"></script>
```
